# Generated by Django 3.1.1 on 2020-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_temp', models.FloatField()),
                ('obj_tmp', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
